[package]
name = "steadq-cli"
description = "SteadQ command-line interface"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "steadq"
path = "src/main.rs"

[dependencies]
libc = "0.2"
steadq-core = { path = "../steadq-core" }
steadq-format = { path = "../steadq-format" }
steadq-names = { path = "../steadq-names" }
steadq-fs-linux = { path = "../steadq-fs-linux" }
clap = { version = "4", features = ["derive"] }
serde.workspace = true
serde_json.workspace = true
