[package]
name = "spoolq-cli"
description = "SpoolQ command-line interface"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "spoolq"
path = "src/main.rs"

[dependencies]
libc = "0.2"
spoolq-core = { path = "../spoolq-core" }
spoolq-format = { path = "../spoolq-format" }
spoolq-names = { path = "../spoolq-names" }
spoolq-fs-linux = { path = "../spoolq-fs-linux" }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
